Creatures-Developer-Network/C2toDS-Refresh

- dev/Scripts/2.0_Aubergine.cos
- dev/Scripts/2.0_Carrots.cos
- dev/Scripts/2.0_Deathcap_Mushroom.cos
- dev/Scripts/2.0_Pears.cos
- dev/Scripts/2.0_Potato.cos
- dev/Scripts/2.0_Triffids.cos
- dev/Scripts/2.0_Trumpet.cos
- dev/Scripts/2.2_Angelfish.cos
- dev/Scripts/2.2_Bees.cos
- dev/Scripts/2.2_Coral.cos
- dev/Scripts/2.2_Crabs.cos
- dev/Scripts/2.2_Goldfish.cos
- dev/Scripts/2.2_Tiger_Barb.cos
- dev/Scripts/2.2_Zanderfish.cos
Made all the stuff classified as detritus edible(with stims), while making deathcap caps also count as detritus, and other smaller misc changes.
Some of these probably will need more work, and critters that have the same classification when dead are not in here.
> Basic Detritus Changes + misc

- dev/Scripts/3.0_Boat.cos
completely redoes boat logic, yay
> Better boat

- dev/Scripts/3.0_Boat.cos
So creatures can start moving about and don't start spamming the button
> Boat removes wait + extra silent stim

- dev/Scripts/3.0_Boat.cos
- dev/Scripts/3.0_Yellow_Raft.cos
Yellow raft now works like the boat(also made it's cabin a bit taller), and fixed some caos typos I made on the boat(shouldn't crash the game now >_>)
> Yellow raft improvements + fixed typos

- dev/Catalogue/c2tods_refresh.catalogue
- dev/Scripts/3.0_Trolly.cos
and fix it getting to low over time
> Make Trolly nav friendly

- dev/Scripts/1.0_1.20.50200_Calendar_Scroll.cos
- dev/Scripts/1.5_Pressure_System_(CA19_Emitters).cos
- dev/Scripts/1.6_Weather.cos
Clouds now rely on the heat CA for movement(They already somewhat did for determining to go up and down it seems), and the CA19 emitters are completely gone.
Atm the clouds seem ok(They probably clump a little more than before as I didn't want them too emit too much heat).
> Remove the need for pressure

- dev/Scripts/1.6_Weather.cos
> add ca option to weather bar

- dev/Scripts/3.0_Boat.cos
- dev/Scripts/3.0_Submarine.cos
Accidently put the unlk for the boat in the loop so creatures could spam it, and added call buttons for the sub.
> Sub nav improvement + Boat fix

- dev/Scripts/1.6_Weather.cos
Floats be weird like this sometimes
> Fix issue were reps could be 0

- dev/Scripts/2.2_Bees.cos
Now they'll follow Flower Marker agents they put near flowers.
> Removed Reliance on Flower Smell

- .gitignore
- dev/Scripts/2.0_Trumpet.cos
Fixes trumpet plant seed migration issues and trumpet plant populations not surviving past the first year.
Fixes #38
> Fix the trumpet plant lifecycle

- dev/Scripts/3.0_Yellow_Raft.cos
> Fix raft moving up overtime bug

- dev/Scripts/1.6_Weather.cos
- dev/Scripts/2.0_Cactus_Spinnomosa.cos
- dev/Scripts/2.0_Grass.cos
- dev/Scripts/2.0_Pears.cos
> inst'ing install scripts

- dev/Scripts/3.0_Yellow_Raft.cos
I.... think a previous fix I did added an unintended side effect
> fixes the raft 'sinking' sometimes

- dev/Catalogue/c2tods_refresh.catalogue
- dev/Scripts/0.1V_World_Extra_Links.cos
- dev/Scripts/1.1_World_CA_Links_&_Fav_Place.cos
- dev/Scripts/3.0_Boat.cos
- dev/Scripts/3.0_Shuttle.cos
- dev/Scripts/3.0_Submarine.cos
- dev/Scripts/3.0_Trolly.cos
- dev/Scripts/3.0_Yellow_Raft.cos
Should make creatures teleporting if moved by the hand from a waiting point a bit less common, if that's common?
Also made the Shuttle a queue agent + fixed all the CA links(and added a separate file for the queue ones for organization)
> Carrying kills the queues + Shuttle & Links update

- dev/Scripts/2.2V_Frog_Pond.cos
- dev/Scripts/2.2V_Norn_Frogs.cos
- dev/Scripts/2.2_Frogs.cos
Fixed some stuff about normal frogs, then made special frogs that can become "frog" norns (currently just bondis), that work liek frog norns for the most part, they don't instant die however, and turn back into frogs when too far from the pond. Their creature history is mostly preserved, more importantly the actual creature is, for reuse when returning to nornhood.
Also life events are tracked as frogs too.
> Frog Norns + Frog Tweaks

- dev/Scripts/1.3_Incubator.cos
Mostly just copied the norn script and replaced specific pose and anim calls with anms and name variables
> Added Custom Eggs Framework Support

- dev/Scripts/2.0_Pears.cos
Moved some stuff around, and hopefully, maybe, fix #33
> Clean-up/fix(?) pears

- dev/Scripts/2.0_Pears.cos
- dev/Scripts/2.2_Frogs.cos
Messed up frog egg eat, should work again, also put in some safety measures for the pears, so they don't try to delete nonexistent things on death
> Pear & Frog fixes

- dev/Scripts/1.2_1.5-7.50200_World_Wrap.cos
- dev/Scripts/2.2_Clams.cos
- dev/Scripts/3.0_Yellow_Raft.cos
World Wrap Changes:
-The world wrap now handles hand holding properly.
Yellow Raft Changes:
-Added a check to see if the creature is autonomous or not to stop the raft sniping creatures out of the hand when dragging them over it.
-Changed TICK 4 to TICK 3 to stop creatures falling through the boat when falling from a great height.
> World Wrap Hand Hold Fix + Yellow Raft Creature Catch Improvements

- dev/Scripts/3.0_Lifts.cos
Change stimulus gotten when pushing a button from #75 (wait) to  #89 (pushed button), as per Creatures Development Standards' recommendation and discussions seen at https://creatures.wiki/Talk:New_lift_script
> Change stimulus when pushing a button to 89

- instinct-friendliness-test(c2ds).cos
Tweak as per https://hello-robotto.dreamwidth.org/5018.html
> Update instinct-friendliness.cos file

- dev/Scripts/1.6_Weather.cos
- dev/Scripts/2.0_Little_Mushrooms.cos
Dustdevils should be rarer, and with the attr check fixed, only move around some things. Also made weather invisible, mushrooms in general not carryable, etc.
> Weather and Mushroom fixes

- dev/Scripts/2.2V_Frog_Pond.cos
- dev/Scripts/2.2V_Norn_Frogs.cos
Genus was too high so it wrapped around, and also tried to fix any problems of ov00 not being set to at least null(Though it not being set at all is kinda a problem so I might have to remove the constructor and put it in the frog scripts if it really is messing up).
> Fix Frog Scripts

- dev/Scripts/2.0_Potato.cos
Adding @babyblueboxers ' suggestion in #116 of changing the starting image of the seed in the detritus eat script.
> Attempt at fixing #116

- dev/Scripts/2.2_Zanderfish.cos
Adding in @babyblueboxers ' suggestion from #114 of adding a size check to the bughunting routine.
> Protecting crabs from extinction by Zanderfish

- dev/Scripts/1.4_Barrier_Doors.cos
> fixed invalid DOOR coords on left sub door

- dev/Scripts/2.2_Crabs.cos
- dev/Scripts/2.2_Dog.cos
-tennis ball no longer auto-deletes when dog dies
-crab no longer checks ov11 on null agents
> crab n dog fixes
